[package]
name = "painter"
version = "0.1.0"
edition = "2024"

[dependencies]
# winit = "0.30.12"
tiny-skia = "0.11.4"
softbuffer = "0.4.8"
anyhow = "1.0"

[dependencies.winit]
version = "0.30.12"
default-features = false
features = ["wayland", "rwh_06"]
